# Generated by Django 5.0.3 on 2024-03-14 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projec',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
